[package]
name = "iced_sequencing"
version = "0.0.1"
authors = ["matthieu gayon <matthieu.gayon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

members = [
    "examples/simple"
]

[dev-dependencies]
iced = "0.2"

[dependencies]
iced_native = "0.3"
iced_graphics = { version = "0.1", features = ["canvas"] }
ganic-no-std = { path = "../ganic_rs-workspace/ganic-no-std" }